### ISSUE TITLE
Missing Stimulation Parameters in Stim reports

### ISSUE THREAD

**Issue by aliixuu** [pennmem/ram_utils#127]
The stimulation parameters section at the top of the report is missing (not filled in). This is the case for R1387E and R1390M most recently. However I do know that it was working about a week ago for R1383J.
<img width="1138" alt="screen shot 2018-01-31 at 3 06 16 pm" src="https://user-images.githubusercontent.com/31287114/35644914-4ca0d9ce-0698-11e8-847b-0f58d30082de.png">

@zduey

**Comment by zduey** [comment]
Looking now

**Comment by zduey** [comment]
@aliixuu -- The ultimate issue in both cases is that the "region" information for the stimulating pair was null and when that table is built, it looks for all unique sets of stimulation parameters excluding null information. Since the region was always null, it was not keeping any rows. 

There are a couple of things to do from here. First, I'll change the logic to only exclude sets of stimulation parameters where *all* fields are null instead of *any*. This will allow that table to still have a row, but region will just be listed as "null." The second thing to do is to review the logic for how we are choosing what location to display, likely with you/Zeinab, Paul, and Youssef. Right now, it defaults to using the "stein" atlas if that exists in the pairs.json file. If "stein" is not an option, then it uses the whole brain atlas for depth electrodes, otherwise it uses the "ind" atlas. The last thing to look into, which is probably a question for @leondavis1 is that for R1390M, there is no LTG15-LTG16 (the stim pair) bipolar pair in pairs.json. I'm not sure if this is a bug or a feature.

If it is okay with you since this requires a couple of logic updates, I think it makes sense to include the fix I mentioned earlier as well as the update to how region information is selected in the next release.

**Comment by zduey** [comment]
Fixed as part of neurorad pipeline
