### ISSUE TITLE
Installation requires setting environment_variable MKL_THREADING_LAYER=GNU

### ISSUE THREAD

**Issue by leondavis1** [pennmem/ram_utils#153]
I created a new python 3.6 environment and installed ram_utils, and when I tried running the report script I got an error that terminated in:

```
  File "/home1/leond/miniconda3/envs/ramutils/lib/python3.6/site-packages/theano/configparser.py", line 332, in __get__
    val_str = self.default()
  File "/home1/leond/miniconda3/envs/ramutils/lib/python3.6/site-packages/theano/configdefaults.py", line 1430, in default_blas_ldflags
    check_mkl_openmp()
  File "/home1/leond/miniconda3/envs/ramutils/lib/python3.6/site-packages/theano/configdefaults.py", line 1252, in check_mkl_openmp
    raise RuntimeError('To use MKL 2018 with Theano you MUST set "MKL_THREADING_LAYER=GNU" in your environement.')
RuntimeError: To use MKL 2018 with Theano you MUST set "MKL_THREADING_LAYER=GNU" in your environement.
```

**Comment by zduey** [comment]
Is this a bug, or should we just have a note in the installation section of the README that indicates that this needs to be set? This is a theano-related requirement that I'm not sure we can automatically do for the user during installation. @mivade do you know of a way to do this that would prevent the user from needing to manually set this variable?

**Comment by mivade** [comment]
I think theoretically conda environments can set environment variables, but I don't know how. That should really be something that the theano package does, though...

A better approach might be to defer importing pymc3 (or whatever is using theano) until it is actually needed since I have a feeling many uses of ramutils aren't actually using that part (that's only part of the HMM stuff, right?).
