### ISSUE TITLE
Update/fix baseline retrieval event identification

### ISSUE THREAD

**Issue by zduey** [pennmem/ram_utils#202]
@LoganJF -- Add more details here.

At the very least we should not be implicitly assuming a sampling rate of 1000 in the current algorithm.

**Comment by LoganJF** [comment]
The main issue here is, as Zach mentioned, that the code incorrectly sets the value for 'eegoffset' for any subject without a sample rate of 1000 in the function insert_baseline_retrieval_events. Attached below is a notebook with an updated version of the function that extracts the sample rate of the subject then will set the eegoffset using that information. 

Additionally, I've included at the end my own personal code for creating matched events. It's much more verbose, but it's functional on RAM/scalp/pyFR data rather than just RAM data (and actually has comments).

https://gist.github.com/LoganJF/dcf040c570bab7a6eb288b991c2df079

**Comment by zduey** [comment]
Closing this as it was fixed in #205
